/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.test_new_project.mytestdatabase;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Table1 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`table1`")
public class Table1 implements Serializable {

    private Integer id;
    private int column2;
    private Table2 table2ByColumn2;
    private List<Table2> table2sForColumn2;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`column2`", nullable = false, scale = 0, precision = 10)
    public int getColumn2() {
        return this.column2;
    }

    public void setColumn2(int column2) {
        this.column2 = column2;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`column2`", referencedColumnName = "`id`", insertable = false, updatable = false)
    public Table2 getTable2ByColumn2() {
        return this.table2ByColumn2;
    }

    public void setTable2ByColumn2(Table2 table2ByColumn2) {
        if(table2ByColumn2 != null) {
            this.column2 = table2ByColumn2.getId();
        }

        this.table2ByColumn2 = table2ByColumn2;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "table1ByColumn2")
    public List<Table2> getTable2sForColumn2() {
        return this.table2sForColumn2;
    }

    public void setTable2sForColumn2(List<Table2> table2sForColumn2) {
        this.table2sForColumn2 = table2sForColumn2;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table1)) return false;
        final Table1 table1 = (Table1) o;
        return Objects.equals(getId(), table1.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

